<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('dashboard');
});

// CRUD resource routes generated by ibex/crud-generator
Route::resource('users', App\Http\Controllers\UserController::class);
Route::resource('biomasas', App\Http\Controllers\BiomasaController::class);
Route::resource('tipo-biomasas', App\Http\Controllers\TipoBiomasaController::class);
// Note: generator created 'SimulacioneController' (singular/plural auto name) — keep the generated name
Route::resource('simulaciones', App\Http\Controllers\SimulacioneController::class);
Route::resource('focos-incendios', App\Http\Controllers\FocosIncendioController::class);
